name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build all packages
        run: go build -v ./...

      - name: Build cmd/painter
        run: go build -v -o painter_app ./cmd/painter

      - name: Test
        run: go test -v ./...
